services:

  api:
    build: .
    container_name: ecom-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    container_name: ecom-worker
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db:
    image: postgres:16
    container_name: ecom-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ecom-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

