services:

  api:
    build: .
    ports:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    container_name: ecom-worker
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db:
    image: postgres:16
    container_name: ecom-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ecom-redis
    ports:
      - "6379:6379"

  nginx:                    # ✅ under services
    image: nginx:alpine
    container_name: ecom-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  postgres_data: